baseURL = "https://xorc.io/"
languageCode = "en-us"
title = "xorc.io | the creators of the xray platform for real-time distributed orchestration "
theme = "navigator-hugo"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "UA-129782477-1"

enableGitInfo = true
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
    logo = "images/xorcio.png"

    # Gestion des langues : FR / EN / NL / DE
    # [[Params.listeLangues]]
    # code = "fr"
  #  [[Params.listeLangues]]
  #  code = "en"

# Gestion des langues : FR / EN / NL / DE
[Languages]
    ############ 1 - Site en FRANCAIS
#    [Languages.fr]
#    weight = 2
#    languageCode = "fr-fr"
#    title = "FRANCAIS Example site multi-language"
#    dateFormat = "2 January 2006"

#    home = "FR Home"
#    logo = "images/logo.png"
#    menufixed = false

#    footerDescription = "FRANCAIS Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
#    footerServiceTitle = "FRANCAIS Services"
#    footerQuicklinkTitle = "FRANCAIS Quick links"
#    footerAboutTitle = "FRANCAIS About"
#    footerSubscribeTitle = "FRANCAIS Subscribe"

#    # Hero Area Section
#    [Languages.fr.params.hero]
#        enable  = true
#        heading = "FRANCAIS We love to make brands grow"
#        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. At quo dolor est incidunt suscipit minima, alias numquam voluptatum rerum porro. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore at laboriosam unde repellat id expedita quae quisquam libero officia consequatur."
#        button  = true
#        btnText = "Know More"
#        btnURL  = "https://themefisher.com/"
#        videoThumb = "images/slider/video-player-thumb.jpg"
#        videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

#    # About 2 Section
#    [Languages.fr.params.aboutSm]
#        enable  = true
#        title   = "FRANCAIS We have explored the digital landscape with passion for a long time"
#        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

#    # Blog Section On Homepage
#    [Languages.fr.params.blog]
#        enable  = true
#        topTitle= "OUR UNTOLD STORY"
#        title   = "FRANCAIS Blog."
#        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

#    # Contact Section
#    [Languages.fr.params.contact]
#        enable  = true
#        topTitle= "DROP US A NOTE"
#        title   = "FRANCAIS Contact Us."
#        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
#        address = "Berlin , Germany"
#        phone   = "(03) 9283 2617"
#        fax     = "+61 3827 3590"
#        facebook= "https://www.facebook.com/"
#        twitter = "https://twitter.com/"
#        linkedin= "https://www.linkedin.com/"
#        dribbble= "https://dribbble.com/"
#        instagram= "https://www.instagram.com/"
#        mapLatitude = "52.520008"
#        mapLongitude= "13.404954"
#        mapMarker   = "images/marker.png"

#    # Call to Action Section on About Page
#    [Languages.fr.params.cta]
#        enable  = true
#        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
#        title   = "FRANCAIS Let's Create Something Together"
#        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
#        btnText = "Nous contacter"

    ############# 2 - Site en ENGLISH
    [Languages.en]
    weight = 1
    languageCode = "en-us"
    title = "Xorc.io - home of the Xray Orchestration Platform"
    dateFormat = "January 2, 2006"

    home = "Home"
    logo = "images/xorcio.png"
    menufixed = false

    footerDescription = "Copyright 2018 xorc.io. All rights reserved"
    footerServiceTitle = "Service"
    footerQuicklinkTitle = "Quicklinks"
    footerAboutTitle = "About"
    footerSubscribeTitle = "Subscribe"

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "Open Source Real-time Distributed Orchestration"
        description = "Automate any complex process running over time with simple combinators capable of modelling anything. Compile programs to run anywhere and respond to signals from any source while persisting states in the cloud. Roll your own simple helpers to connect to external services in any JVM compliant language."
        button  = true
        btnText = "Get the code"
        btnURL  = "https://github.com/xray-tech/"
        videoThumb = "/images/world-mesh.png"
        # videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable  = true
        title   = "Create an environment as unique as your use case around our Open Source Realtime Core "
        description = "By adding a layer of connectors, standard programmes and maybe even a simple API wrapped around our Open Source rule engine, you can rapidly prototype your business ideas without having to devote years of developer time to ensure your workflows are run from start to end reliably, repeatedly and at scale. We even give you a headstart in mobile with Open Source Mobile SDK and connectors for Android and iOS messaging as well as http to make it easy to call existing services with program state changes and outcomes."


    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "GET INVOLVED"
        title   = "Become a contributor"
        subtitle= "Most of the team is currently based in Berlin but the home of this project is GitHub so feel free to submit your issues and comments there, taking the time to read our contributors' guide when you are ready to jump in with a fix or new features."
        address = "Reach out to the team if you need any extra help or litarature before being able to convince your team or backers that this is the right software for you, we'll be happy to lend a hand or share our insights."
        # phone   = "(03) 9283 2617"
        # fax     = "+61 3827 3590"
      #   facebook= "https://www.facebook.com/"
      #  twitter = "https://twitter.com/"
      #  linkedin= "https://www.linkedin.com/"
      #  dribbble= "https://dribbble.com/"
      #  instagram= "https://www.instagram.com/"
      mapLatitude = "52.520008"
      mapLongitude= "13.404954"
        mapMarker   = "images/marker.png"


    [Languages.en.params.know_more]
        enable  = true
        topTitle= "Really deep"
        title   = "Digging Deeper"
   

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
  #  [[menu.nav]]
  #      name    = "service"
  #      url     = "service"
  #      weight  = 3
    # [[menu.nav]]
    #    name    = "portfolio"
    #    url     = "portfolio"
    #    weight  = 4
    [[menu.nav]]
        name    = "team"
        url     = "team"
        weight  = 5
    [[menu.nav]]
        name    = "contribute"
        url     = "contribute"
        weight  = 6

    # Footer Service Menu
    [[menu.service]]
        name    = "graphicdesign"
        url     = "service"
        weight  = 1
    [[menu.service]]
        name    = "webdesign"
        url     = "service"
        weight  = 2
    [[menu.service]]
        name    = "webdevelopment"
        url     = "service"
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "partners"
        url     = "about"
        weight  = 1
    [[menu.quicklink]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.quicklink]]
        name    = "faqs"
        url     = "about"
        weight  = 3
    [[menu.quicklink]]
        name    = "badges"
        url     = "about"
        weight  = 4
